# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alpha.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(0.85)
        MainWindow.setStyleSheet("border: 1px solid #fff;\n"
"background-color: rgb(170, 191, 208);\n"
"border-radius: 16px;\n"
"border-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(300, 10, 40, 40))
        self.btn_close.setStyleSheet("background-color: rgb(249, 255, 255);")
        self.btn_close.setObjectName("btn_close")
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(10, 10, 230, 41))
        self.version.setStyleSheet("background-color: rgb(249, 255, 255);\n"
"font: 75 32pt \"System\";")
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        self.btn_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minimize.setGeometry(QtCore.QRect(250, 10, 40, 40))
        self.btn_minimize.setStyleSheet("background-color: rgb(249, 255, 255);")
        self.btn_minimize.setObjectName("btn_minimize")
        self.List = QtWidgets.QListWidget(self.centralwidget)
        self.List.setGeometry(QtCore.QRect(10, 60, 330, 490))
        self.List.setStyleSheet("background-color: rgb(249, 255, 255);")
        self.List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.List.setObjectName("List")
        self.Switch = QtWidgets.QPushButton(self.centralwidget)
        self.Switch.setGeometry(QtCore.QRect(110, 564, 130, 41))
        self.Switch.setStyleSheet("background-color: rgb(249, 255, 255);\n"
"font: 15pt \"Nirmala UI\";\n"
"font: 75 32pt \"System\";")
        self.Switch.setObjectName("Switch")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(295, 564, 40, 40))
        self.status.setStyleSheet("background-color: rgb(209, 123, 117);")
        self.status.setText("")
        self.status.setObjectName("status")
        self.sets_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sets_btn.setGeometry(QtCore.QRect(10, 565, 41, 41))
        self.sets_btn.setStyleSheet("background-color: rgb(249, 255, 255);")
        self.sets_btn.setObjectName("sets_btn")
        self.version_2 = QtWidgets.QLabel(self.centralwidget)
        self.version_2.setGeometry(QtCore.QRect(360, 10, 320, 40))
        self.version_2.setStyleSheet("background-color: rgb(249, 255, 255);\n"
"font: 75 32pt \"System\";")
        self.version_2.setAlignment(QtCore.Qt.AlignCenter)
        self.version_2.setObjectName("version_2")
        self.version_3 = QtWidgets.QLabel(self.centralwidget)
        self.version_3.setGeometry(QtCore.QRect(360, 350, 320, 40))
        self.version_3.setStyleSheet("background-color: rgb(249, 255, 255);\n"
"font: 75 32pt \"System\";")
        self.version_3.setAlignment(QtCore.Qt.AlignCenter)
        self.version_3.setObjectName("version_3")
        self.logs_plain = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logs_plain.setGeometry(QtCore.QRect(360, 400, 320, 205))
        self.logs_plain.setStyleSheet("background-color: rgb(249, 255, 255);\n"
"font: 75 12pt \"System\";")
        self.logs_plain.setPlainText("")
        self.logs_plain.setObjectName("logs_plain")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 60, 320, 280))
        self.groupBox.setStyleSheet("background-color: rgb(249, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 281, 17))
        self.checkBox.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 50, 281, 17))
        self.checkBox_2.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 80, 281, 17))
        self.checkBox_3.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.checkBox_3.setCheckable(True)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 110, 281, 17))
        self.checkBox_4.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 140, 281, 17))
        self.checkBox_5.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.checkBox_5.setCheckable(True)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 170, 131, 21))
        self.label.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(180, 173, 121, 20))
        self.horizontalSlider.setStyleSheet("border: 0px;\n"
"")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(5)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setProperty("value", 85)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 51, 21))
        self.label_2.setStyleSheet("border: 0px;\n"
"font: 75 32pt \"System\";")
        self.label_2.setObjectName("label_2")
        self.city_lineedit = QtWidgets.QLineEdit(self.groupBox)
        self.city_lineedit.setGeometry(QtCore.QRect(80, 200, 131, 21))
        self.city_lineedit.setObjectName("city_lineedit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(220, 200, 91, 21))
        self.label_3.setStyleSheet("border: 0px;\n"
"color: rgb(85, 85, 85);\n"
"font: 75 32pt \"System\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_close.setText(_translate("MainWindow", "x"))
        self.version.setText(_translate("MainWindow", "*Название*"))
        self.btn_minimize.setText(_translate("MainWindow", "-"))
        self.Switch.setText(_translate("MainWindow", "On | Off"))
        self.sets_btn.setText(_translate("MainWindow", "..."))
        self.version_2.setText(_translate("MainWindow", "Настройки"))
        self.version_3.setText(_translate("MainWindow", "Логи"))
        self.checkBox.setText(_translate("MainWindow", "Тихий режим"))
        self.checkBox_2.setText(_translate("MainWindow", "Настройка 2"))
        self.checkBox_3.setText(_translate("MainWindow", "Настройка 3"))
        self.checkBox_4.setText(_translate("MainWindow", "Настройка 4"))
        self.checkBox_5.setText(_translate("MainWindow", "Настройка 5"))
        self.label.setText(_translate("MainWindow", "Прозрачность окна"))
        self.label_2.setText(_translate("MainWindow", "Город:"))
        self.label_3.setText(_translate("MainWindow", "(для погоды)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
