# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
Просто код сгенерированнный QtDesigner
Его НЕ ТРОГАТЬ, лишь наследовать класс в main.py
и там проводить всякую херь, для того чтобы можно было без лишних проблем
обновить интерфейс
"""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 620)
        MainWindow.setStyleSheet("border: 2px solid #fff;\n"
"border-radius: 16px;\n"
"border-color: rgb(148, 197, 191);\n"
"background-color: rgb(88, 123, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(300, 10, 40, 40))
        self.btn_close.setStyleSheet("background-color: rgb(152, 193, 184);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_close.setObjectName("btn_close")
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(10, 10, 230, 40))
        self.version.setStyleSheet("background-color: rgb(152, 193, 184);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 11pt \"Arial Black\";")
        self.version.setAlignment(QtCore.Qt.AlignCenter)
        self.version.setObjectName("version")
        self.btn_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minimize.setGeometry(QtCore.QRect(250, 10, 40, 40))
        self.btn_minimize.setStyleSheet("background-color: rgb(152, 193, 184);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn_minimize.setObjectName("btn_minimize")
        self.List = QtWidgets.QListWidget(self.centralwidget)
        self.List.setGeometry(QtCore.QRect(10, 60, 330, 490))
        self.List.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.494773, y1:1, x2:0.494318, y2:0, stop:0 rgba(181, 197, 195, 255), stop:0.903409 rgba(88, 123, 116, 255));")
        self.List.setObjectName("List")
        self.List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Switch = QtWidgets.QPushButton(self.centralwidget)
        self.Switch.setGeometry(QtCore.QRect(139, 564, 76, 41))
        self.Switch.setStyleSheet("background-color: rgb(152, 193, 184);\n"
"font: 87 11pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.Switch.setObjectName("Switch")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(295, 564, 40, 40))
        self.status.setStyleSheet("background-color: rgb(209, 123, 117);")
        self.status.setText("")
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_close.setText(_translate("MainWindow", "x"))
        self.version.setText(_translate("MainWindow", "Voice Assistant V4"))
        self.btn_minimize.setText(_translate("MainWindow", "-"))
        self.Switch.setText(_translate("MainWindow", "On | Off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
